KUROYURI_PATH: kuroyuri.png
THRESHOLD_RATIO: 0.97

# !使用时请只保留一份配置，其他请注释！

# 配置1: 默认设置 (9*16)
DEFAULT_WIDTH: 1080
DEFAULT_HEIGHT: 1920
CROP_X1_RATIO: 0.872
CROP_Y1_RATIO: 0.809
CROP_X2_RATIO: 0.94
CROP_Y2_RATIO: 0.85
SLIDE_X1_RATIO: 0.074
SLIDE_Y1_RATIO: 0.672
SLIDE_X2_RATIO: 0.888
SLIDE_Y2_RATIO: 0.839

# 配置2: 2340*1080
# DEFAULT_WIDTH: 1080
# DEFAULT_HEIGHT: 2340
# CROP_X1_RATIO: 0.872
# CROP_Y1_RATIO: 0.757
# CROP_X2_RATIO: 0.945
# CROP_Y2_RATIO: 0.794
# SLIDE_X1_RATIO: 0.082
# SLIDE_Y1_RATIO: 0.641
# SLIDE_X2_RATIO: 0.884
# SLIDE_Y2_RATIO: 0.773